version: 2

jobs:

  newman:
    docker:
      - image: circleci/node:8.6
    working_directory: ~/w
    steps:
      - checkout
      - run: yarn
      - run: yarn run test:newman
      - persist_to_workspace:
          root: ~/w
          paths:
            - node_modules


workflows:
  version: 2
  build:
    jobs:
      - newman
